services:
    mbartok_entity_describer.manager:
        class: mbartok\EntityDescriberBundle\Manager\EntityDescriberManager
    mbartok_entity_describer.twig.entity_describer:
        class: mbartok\EntityDescriberBundle\Twig\EntityDescriberExtension
        arguments:
            - "@mbartok_entity_describer.manager"
            - "@router"
        tags:
            - { name: twig.extension }